-keepattributes Signature, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keep class androidx.compose.** { *; }
-dontwarn androidx.compose.**
-keep class com.smartassistant.app.data.local.entity.** { *; }
-keep class com.smartassistant.app.data.local.dao.** { *; }
-keep class * extends androidx.room.RoomDatabase { *; }
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepclassmembers class kotlinx.coroutines.** { volatile <fields>; }
-keep class * extends androidx.lifecycle.ViewModel { *; }
-keep class androidx.navigation.** { *; }
-keep class coil.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class androidx.datastore.** { *; }
-keep class com.tom_roush.** { *; }
-keep class org.apache.** { *; }
-keep class org.bouncycastle.** { *; }
-keep class com.gemalto.** { *; }
-dontwarn com.tom_roush.**
-dontwarn org.apache.**
-dontwarn com.gemalto.**
-dontwarn javax.xml.bind.**
-dontwarn java.awt.**
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**
-dontwarn com.google.android.gms.**
-keep class androidx.core.splashscreen.** { *; }
-keep class androidx.compose.material.icons.** { *; }
-keep class com.smartassistant.app.importer.** { *; }
